version: 0.0
os: linux
files:
    - source: /
      destination: /app/nodeappexample
hooks:
#  ApplicationStop:
#    - location: deployment.js
#      timeout: 180
  BeforeInstall:
    - location: install_dependencies
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start_server
      timeout: 180
      runas: root
  ValidateService:
    + location: stop_server
      timeout: 180
      runas: root
