name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "master" ]  # or "main" if that's your actual branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests (skip if not defined)
        run: |
          if [ -f package.json ] && grep -q "\"test\"" package.json; then
            npm test
          else
            echo "No test script found, skipping tests."
          fi

      - name: Build Docker Image
        run: docker build -t bhargavbtk/devops_task1 .

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Image
        run: docker push bhargavbtk/devops_task1
